### PR TITLE
feat: Add environment section in job definition to enable user to add manual approval gate for deploy jobs

### PR DESCRIPTION
**Pull request by liweiyi88**
Adds environment section in deploy jobs so it will give people a chance to set up a manual approval gate if they like.

### CODE REVIEW

**Comment by kaizen3031593** [comment]
Hi @liweiyi88, thanks for submitting this PR! What you've added is interesting but I'd like to dive in to what feature you're trying to unlock first. In the code it looks like you just want to add an environment variable, and I'm curious how that might lead to a manual approval gate.

This might be best discussed via a github issue. Do you mind submitting an issue that to propose the change you want to make as well as the use case it unlocks? Thanks.

**Comment by kaizen3031593** [comment]
Hi @liweiyi88, thanks for submitting this PR! What you've added is interesting but I'd like to dive in to what feature you're trying to unlock first. In the code it looks like you just want to add an environment variable, and I'm curious how that might lead to a manual approval gate.

This might be best discussed via a github issue. Do you mind submitting an issue that to propose the change you want to make as well as the use case it unlocks? Thanks.

**Comment by liweiyi88** [comment]
@kaizen3031593 sure thing, I have added the description in #162 . Please let me know if you have any further questions Thanks.

**Comment by liweiyi88** [comment]
closed as we provided an extra api to enable this #178

**Pull request closed without merging**
