### PR TITLE
chore: Update `yaml` dependency to latest

### PR DESCRIPTION
**Pull request by giseburt**
Part 1 of 2 for #349

All test passed locally, no new tests appear to be needed.

### CODE REVIEW

**Review by kaizencc — APPROVED** [review]
Thanks!

**Comment by kaizencc** [comment]
@giseburt, you need to run `yarn build` locally and update the snapshots, I can't do it for you because your `main` branch is protected

**Comment by giseburt** [comment]
Ok. I was about to but saw you were pushing code and don't want to conflict. I'll do that shortly.

**Comment by giseburt** [comment]
@kaizencc Ok, should be good now.

I'm not sure why the test snapshots needed updated. This change shouldn't have triggered that, but I adjusted anyway.

BTW, unrelated issue: ` --updateSnapshot` shouldn't be on the `jest` command for testing ([here](https://github.com/cdklabs/cdk-pipelines-github/blob/main/.projen/tasks.json#L242)) - that will make any test with a snapshot _always_ pass  since it'll just update the snapshot and pass it.

**Comment by kaizencc** [comment]
@giseburt it must be that yaml 2.0 handles undefined objects differently. Looks like previously, `container: undefined` would render as `container: null` and now it is omitted entirely. I think this is okay, given the experimental nature of this module, people should be fine that their `deploy.yml` files change in a insignificant way.

**Pull request merged**
